// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomId: __t.string().name("room_id"),
  displayName: __t.string().name("display_name"),
  seatIndex: __t.i32().name("seat_index"),
  online: __t.bool(),
  connectedAt: __t.timestamp().name("connected_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
