// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const HandState = __t.object("HandState", {
  identity: __t.identity(),
  roomId: __t.string(),
  poseJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type HandState = __Infer<typeof HandState>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomId: __t.string(),
  displayName: __t.string(),
  seatIndex: __t.i32(),
  online: __t.bool(),
  connectedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const WebrtcSignal = __t.object("WebrtcSignal", {
  id: __t.u64(),
  roomId: __t.string(),
  senderId: __t.identity(),
  recipientId: __t.identity(),
  kind: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type WebrtcSignal = __Infer<typeof WebrtcSignal>;

