// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ConsumeWebrtcSignalReducer from "../consume_webrtc_signal_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import RequestSeatReducer from "../request_seat_reducer";
import SendWebrtcSignalReducer from "../send_webrtc_signal_reducer";
import UpdateCreatureReducer from "../update_creature_reducer";
import UpdateInstrumentReducer from "../update_instrument_reducer";

export type ConsumeWebrtcSignalParams = __Infer<typeof ConsumeWebrtcSignalReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type RequestSeatParams = __Infer<typeof RequestSeatReducer>;
export type SendWebrtcSignalParams = __Infer<typeof SendWebrtcSignalReducer>;
export type UpdateCreatureParams = __Infer<typeof UpdateCreatureReducer>;
export type UpdateInstrumentParams = __Infer<typeof UpdateInstrumentReducer>;

