// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import LeaveRoomReducer from "../leave_room_reducer";
import RequestSeatReducer from "../request_seat_reducer";
import UpdatePoseReducer from "../update_pose_reducer";

export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type RequestSeatParams = __Infer<typeof RequestSeatReducer>;
export type UpdatePoseParams = __Infer<typeof UpdatePoseReducer>;

